######################################################################
# Automatically generated by qmake (3.0) Fri Mar 20 14:19:13 2015
######################################################################

INCLUDEPATH += $$PWD

#HEADERS += \
PRECOMPILED_HEADER += \
  $$PWD/objMesh-disjointSet.h \
  $$PWD/objMesh.h \
  $$PWD/objMeshRender.h \
  $$PWD/macros.h \

SOURCES += \
  $$PWD/objMesh-disjointSet.cpp \
  $$PWD/objMesh.cpp \
  $$PWD/objMeshRender.cpp \
