######################################################################
# Automatically generated by qmake (3.0) Thu Mar 19 16:11:08 2015
######################################################################

INCLUDEPATH += $$PWD

HEADERS += \
  $$PWD/cbmp.h \
  $$PWD/pconsole.h \
  $$PWD/simOBJ.h \
  $$PWD/strmanip.h \

SOURCES += \
    $$PWD/pconsole.cpp \
    $$PWD/simOBJ.cpp
